"""Строки интерфейса, которых нет в версии для Mac.

Добавляются к общим `core.UI_STRINGS` вызовом install(). Коротко: люди это видят
на бегу, объяснения ограничений только отвлекают.
"""

from . import core

WIN_STRINGS = {
    "ru": {
        "mic_title": "Микрофон недоступен",
        "mic_msg": "Проверь, что микрофон подключён и не занят другой программой.",
        "mic_blocked": "Микрофон выключен",
        "mic_blocked_msg": "Разреши доступ: Параметры → Конфиденциальность → Микрофон.",
        "paste_blocked_title": "Не вставилось",
        "paste_blocked_msg": "Текст в буфере обмена — нажми Ctrl+V.",
        "error_title": "Ошибка распознавания",
        "hk_err_empty": "Нажми клавишу или сочетание",
        "hk_err_too_many": "Не больше трёх клавиш",
        "hk_err_reserved": "Esc и Enter уже заняты",
        "hk_err_typing": "Эта клавиша нужна для набора текста — добавь Ctrl или Alt",
        "hk_warn_alt": "Alt в программах открывает меню",
        "hk_warn_win": "Win открывает меню «Пуск»",
        "hk_warn_shift": "Shift нужен для заглавных букв",
        "st_ready": "Готово — зажми {key} и говори",
        "st_loading": "Запускаю модель…",
        "st_download": "Скачиваю модель {model}… {pct}",
        "st_switch": "Перехожу на модель {model}…",
        "st_error": "Модель не запустилась",
        "st_hook_error": "Клавиша диктовки не работает",
        "st_paused": "На паузе",
        "st_recording": "Слушаю…",
        "model_auto": "Авто",
        "lang_auto": "Определять сам",
        "mb": "МБ",
        "menu_pause": "Пауза",
        "menu_quit": "Выход",
        "ready_title": "LocalFlow готов",
        "ready_msg": "Зажми {key} и говори",
        "key_left": "левый {key}",
        "key_right": "правый {key}",
        "model_failed": "Модель {model} не запустилась — вернул прежнюю",
        "menu_settings": "Настройки…", "mic_default": "Как в системе", "idle_never": "Никогда",
    },
    "en": {
        "mic_title": "Microphone unavailable",
        "mic_msg": "Check that the microphone is connected and not used by another app.",
        "mic_blocked": "Microphone is off",
        "mic_blocked_msg": "Allow access: Settings → Privacy → Microphone.",
        "paste_blocked_title": "Couldn't paste",
        "paste_blocked_msg": "The text is on the clipboard — press Ctrl+V.",
        "error_title": "Transcription error",
        "hk_err_empty": "Press a key or a combination",
        "hk_err_too_many": "Three keys at most",
        "hk_err_reserved": "Esc and Enter are already taken",
        "hk_err_typing": "This key is needed for typing — add Ctrl or Alt",
        "hk_warn_alt": "Alt opens menus in apps",
        "hk_warn_win": "Win opens the Start menu",
        "hk_warn_shift": "Shift is needed for capital letters",
        "st_ready": "Ready — hold {key} and speak",
        "st_loading": "Starting the model…",
        "st_download": "Downloading model {model}… {pct}",
        "st_switch": "Switching to model {model}…",
        "st_error": "The model didn't start",
        "st_hook_error": "The dictation key isn't working",
        "st_paused": "Paused",
        "st_recording": "Listening…",
        "model_auto": "Auto",
        "lang_auto": "Detect automatically",
        "mb": "MB",
        "menu_pause": "Pause",
        "menu_quit": "Quit",
        "ready_title": "LocalFlow is ready",
        "ready_msg": "Hold {key} and speak",
        "key_left": "Left {key}",
        "key_right": "Right {key}",
        "model_failed": "Model {model} didn't start — back to the previous one",
        "menu_settings": "Settings…", "mic_default": "System default", "idle_never": "Never",
    },
    "uk": {
        "mic_title": "Мікрофон недоступний",
        "mic_msg": "Перевір, що мікрофон підключений і не зайнятий іншою програмою.",
        "mic_blocked": "Мікрофон вимкнено",
        "mic_blocked_msg": "Дозволь доступ: Параметри → Конфіденційність → Мікрофон.",
        "paste_blocked_title": "Не вставилося",
        "paste_blocked_msg": "Текст у буфері обміну — натисни Ctrl+V.",
        "error_title": "Помилка розпізнавання",
        "hk_err_empty": "Натисни клавішу або поєднання",
        "hk_err_too_many": "Не більше трьох клавіш",
        "hk_err_reserved": "Esc і Enter уже зайняті",
        "hk_err_typing": "Ця клавіша потрібна для набору тексту — додай Ctrl або Alt",
        "hk_warn_alt": "Alt у програмах відкриває меню",
        "hk_warn_win": "Win відкриває меню «Пуск»",
        "hk_warn_shift": "Shift потрібен для великих літер",
        "st_ready": "Готово — затисни {key} і говори",
        "st_loading": "Запускаю модель…",
        "st_download": "Завантажую модель {model}… {pct}",
        "st_switch": "Переходжу на модель {model}…",
        "st_error": "Модель не запустилася",
        "st_hook_error": "Клавіша диктування не працює",
        "st_paused": "На паузі",
        "st_recording": "Слухаю…",
        "model_auto": "Авто",
        "lang_auto": "Визначати сам",
        "mb": "МБ",
        "menu_pause": "Пауза",
        "menu_quit": "Вихід",
        "ready_title": "LocalFlow готовий",
        "ready_msg": "Затисни {key} і говори",
        "key_left": "лівий {key}",
        "key_right": "правий {key}",
        "model_failed": "Модель {model} не запустилася — повернув попередню",
        "menu_settings": "Налаштування…", "mic_default": "Як у системі", "idle_never": "Ніколи",
    },
    "de": {
        "mic_title": "Mikrofon nicht verfügbar",
        "mic_msg": "Prüfe, ob das Mikrofon angeschlossen und frei ist.",
        "mic_blocked": "Mikrofon ist aus",
        "mic_blocked_msg": "Zugriff erlauben: Einstellungen → Datenschutz → Mikrofon.",
        "paste_blocked_title": "Nicht eingefügt",
        "paste_blocked_msg": "Der Text ist in der Zwischenablage — drücke Strg+V.",
        "error_title": "Erkennungsfehler",
        "hk_err_empty": "Drücke eine Taste oder Kombination",
        "hk_err_too_many": "Höchstens drei Tasten",
        "hk_err_reserved": "Esc und Enter sind schon belegt",
        "hk_err_typing": "Diese Taste braucht man zum Tippen — nimm Strg oder Alt dazu",
        "hk_warn_alt": "Alt öffnet in Programmen das Menü",
        "hk_warn_win": "Win öffnet das Startmenü",
        "hk_warn_shift": "Shift braucht man für Großbuchstaben",
        "st_ready": "Bereit — {key} halten und sprechen",
        "st_loading": "Modell startet…",
        "st_download": "Lade Modell {model}… {pct}",
        "st_switch": "Wechsle zu Modell {model}…",
        "st_error": "Das Modell ist nicht gestartet",
        "st_hook_error": "Die Diktiertaste funktioniert nicht",
        "st_paused": "Pausiert",
        "st_recording": "Höre zu…",
        "model_auto": "Auto",
        "lang_auto": "Automatisch erkennen",
        "mb": "MB",
        "menu_pause": "Pause",
        "menu_quit": "Beenden",
        "ready_title": "LocalFlow ist bereit",
        "ready_msg": "{key} halten und sprechen",
        "key_left": "{key} links",
        "key_right": "{key} rechts",
        "model_failed": "Modell {model} ist nicht gestartet — zurück zum vorherigen",
        "menu_settings": "Einstellungen…", "mic_default": "Wie im System", "idle_never": "Nie",
    },
}


def install() -> None:
    for lang, items in WIN_STRINGS.items():
        core.UI_STRINGS.setdefault(lang, {}).update(items)
